title: Tanzconnective
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  We are the Tanzconnective.
baseurl: "/tanzconnective" # the subpath of your site, e.g. /blog
url: "rammelmueller.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed